Module user
OrifInformatique/ci_packbase_v4 pull request #21
Opened 2021-03-19 12:40 UTC by maximeor

2021-03-24 12:06 UTC, DidierViret commented on app/Config/Filters.php
> +use App\Controllers\BaseController;
Finalement est-ce que ces filtres sont utilisés ? et où ?

2021-03-26 10:53 UTC, maximeor commented on app/Config/App.php
>  	 * --------------------------------------------------------------------------
tester

2021-03-26 10:56 UTC, DidierViret requested changes

2021-03-26 10:56 UTC, DidierViret commented on app/Config/Filters.php
> +use App\Controllers\BaseController;
Non ils ne sont pas utilisés, suppression des références.

2021-03-26 11:58 UTC, maximeor commented on orif/user/Config/Routes.php
> +$routes->group("user/admin",function($routes){
Oui, elle consiste à ajouter les routes comme ceci,
$routes->add('user/auth/(:any)','\User\Controllers\Auth::$1');

$routes->add('user/admin/(:any)','\User\Controllers\Admin::$1');

2021-03-26 12:02 UTC, DidierViret commented on orif/user/Config/Routes.php
> +$routes->group("user/admin",function($routes){
Parfait alors vous pouvez remplacer par cette manière de faire, c'est mieux à mon avis.

2021-03-26 13:55 UTC, DidierViret requested changes

2021-03-26 13:55 UTC, DidierViret commented on orif/user/Database/Migrations/2021-03-19-090830_add_ci_sessions.php
> +                'type'              => 'INT',
Selon la documentation de CodeIgniter, le champ "id" de la table ci_sessions doit être du type varchar(128).
A corriger.

2021-03-26 14:34 UTC, DidierViret commented on orif/user/Models/User_model.php
> +    protected $allowedFields=['archive','created_date','email','firstname','is_active','lastname','password','username','fk_user_type'];
La variable allowedFields contient des noms de champs qui n'existent pas dans la base de donnée.

2021-03-26 15:23 UTC, DidierViret requested changes

2021-03-26 15:23 UTC, DidierViret commented on orif/user/Models/User_model.php
> +    protected $allowedFields=['archive','created_date','email','firstname','is_active','lastname','password','username','fk_user_type'];
La variable allowedFields contient des noms de champs qui n'existent pas dans la base de donnée.

2021-03-31 08:44 UTC, maximeor commented on orif/user/Controllers/Admin.php
> +            'user_types' => $this->user_type_model->findColumn('name'),
Ok, cette modif a été éffectuée

2021-03-31 08:49 UTC, maximeor commented on orif/user/Views/admin/list_user.php
> +                    <td><?= $user_types[$user['fk_user_type']-1]; ?></td>
Cette modif est faite

2021-03-31 10:52 UTC, maximeor commented on orif/user/Controllers/Admin.php
> +        $oldName = NULL;
elles permettent de réafficher les données sasies si elles ne correspondent pas aux règles de validation

2021-03-31 10:55 UTC, maximeor commented on orif/user/Database/Migrations/2021-03-19-090830_add_ci_sessions.php
> +                'type'              => 'INT',
ceci est corrigé

2021-04-22 09:47 UTC, DidierViret approved these changes

2021-04-22 09:48 UTC, merged